//
// Filename: layout.tsx
// Description: Site-wide layout
// Copyright (c) 2026 Team Vibes
// Authors: Ethan Gao, Nathan Smith, Ryan Smith, and Tianyi Wang
//

import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { JSX } from "react";
import { SpeedInsights } from "@vercel/speed-insights/next"

import "./globals.css";
import "@/lib/ui/endings/ending-screen.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">): JSX.Element {
	return (
		<html
			lang="en"
			className={`bg-background text-foreground h-full antialiased ${geistSans.variable} ${geistMono.variable}`}
		>
			<body className="min-h-screen flex flex-col">
				{children}
			</body>

			<Analytics/>
			<SpeedInsights/>
		</html>
	);
}
